name: 'Convox Deploy'
description: 'Build and Deploy a Convox app in a single step'
author: 'Convox'
inputs:
  password:
    description: 'Convox deploy key value'
    required: true
  host:
    description: 'Convox Console host address'
    required: true
    default: 'console.convox.com'
  app:
    description: 'Convox app name'
    required: true
  rack:
    description: 'Convox Rack name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'