name: 'Convox Run'
description: 'Run a command against a Release of a Convox App'
author: 'Convox'
inputs:
  password:
    description: 'Convox deploy key value'
    required: true
  host:
    description: 'Convox Console host address'
    required: true
    default: 'console.convox.com'
  app:
    description: 'Convox app name'
    required: true
  rack:
    description: 'Convox Rack name'
    required: true
  command:
    description: 'The command to be run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'